import praw_comments_500

comments = praw_comments_500.comments

# Movies to look for in the set
search = [
    ["Anastasia"],
    ["Hook", "Mouse Hunt", "Titanic"],
    ["Treasure Planet"],
    ["Ever After"],
    ["Galaxy Quest"],
    ["Secret of  Nimh"],
    ["Secondhand Lions"],
    ["Cool Runnings"],
    ["A Little Princess"],
    ["Indiana Jones"],
    ["Big Trouble in Little China"],
    ["Stand By Me"],
    ["Practical Magic"],
    ["Clue"],
    ["How to Train Your Dragon", "Test Drive", "Forbidden Frienship"],
    ["BeetleJuice"],
    ["A knights tale"],
    ["Ratatouille"],
    ["Office Space"],
    ["Stardust"],
    ["The Last Unicorn"],
    ["My Cousin Vinny"],
    ["The Iron Giant"],
    ["Pleasantville"],
    ["Tremors"],
    ["The princess bride"],
    ["Empire Records", "Labyrinth"],
    ["Wallace and Gromit"],
    ["O Brother Where Art Thou"],
    ["Blazing Saddles"],
    ["Starship troopers"],
    ["The Lost Boys"],
    ["Pan's Labyrinth"],
    ["Who Framed Roger Rabbit"],
    ["Goodfellas"],
    ["Constantine"],
    ["Little Rascals"],
    ["Kubo and The Two Strings"],
    ["The prince of egypt"],
    ["The Incredibles"],
    ["The Fall"],
    ["Labyrinth"],
    ["Jungle Book", "Clerks"],
    ["Chicken Run"],
    ["Armageddon"],
    ["Matilda"],
    ["12 Angry Men"],
    ["Willow"],
    ["Shaun of the Dead"],
    ["THE MUMMY"],
    ["The Land Before Time"],
    ["National Lampoon's Christmas Vacation"],
    ["Babe"],
    ["Fievel Goes West"],
    ["Howl's Moving Castle"],
    ["The Hunchback of Notre Dame"],
    ["Jurassic Park"],
    ["Big Fish"],
    ["Tangled"],
    ["Blade"],
    ["Brother Bear"],
    ["A league of their own"],
    ["Jurassic Park"],
    ["Edward Scissorhands"],
    ["Wall-E"],
    ["Monty Python and the Holy Grail"],
    ["Fantastic mr fox"],
    ["The Neverending Story"],
    ["Anne of Green Gables"],
    ["Robin Hood"],
    ["The Fifth Element"],
    ["The Goonies"],
    ["Pirates of the Caribbean: curse of the Black Pearl"],
    ["Titan A.E."],
    ["Snatch"],
    ["Real Genius"],
    ["Let the Right One In"],
    ["Back to the Future"],
    ["Amelie"],
    ["Cirque du Soleil: Worlds Away"],
    ["My Neighbor Totoro"],
    ["True Lies"],
    ["Ponyo"],
    ["A Goofy Movie"],
    ["Wreck It Ralph"],
    ["National Treasure"],
    ["nightmare before christmas"],
    ["Excellent Adventure", "Bogus Journey", "Face the Music"],
    ["Catch Me If You Can"],
    ["How to train your dragon"],
    ["Drop Dead Fred"],
    ["SHREK"],
    ["Emperor's New Groove"],
    ["School of rock"],
    ["Ferris Bueller's Day Off"],
    ["Atlantis"],
    ["A fish called Wanda"],
    ["Rear Window"],
    ["The Princess Bride"],
    ["Big Fish"],
    ["The craft"],
    ["Jumanji"],
    [
        "The Black Stallion",
        "The Sound of Music",
        "Pride & Prejudice",
        "Princess Mononoke",
        "Seven Samurai",
    ],
    ["The Goonies"],
    ["Blues Brothers"],
    ["Mary Poppins"],
    ["Now and Then"],
    ["Fantasia"],
    ["Jurassic Park"],
    ["Clue"],
    ["Singin in the rain"],
    ["Room"],
    ["Notting Hill", "Pretty Woman"],
    ["Perfume: The Story of a Murderer"],
    ["Howls Moving castle"],
    ["eurotrip"],
    ["The Dark Crystal"],
    ["The Fifth Element"],
    ["V for Vendetta"],
    ["Stardust"],
    ["Shawshank Redemption"],
    ["Almost Famous"],
    ["Stargate"],
    ["The Brave Little Toaster"],
    ["Lord of the Rings"],
    ["Coraline"],
    ["Field of Dreams"],
    ["The Grand Budapest Hotel"],
    ["The Mask"],
    ["Best in Show"],
    ["Dune"],
    ["Knight's Tale"],
    ["Clueless"],
    ["Holes"],
    ["Clerks"],
    ["Forrest Gump"],
    ["The Matrix"],
    ["Dogma"],
    ["Children of men", "Last of the Mohicans", "Mars Attacks"],
    ["A Silent Voice"],
    ["Dead Poets Society"],
    ["Dark Crystal"],
    ["Seven Brides for Seven Brothers"],
    ["Dazed and Confused"],
    ["The Secret of Kells"],
    ["Grave of the fireflies"],
    ["Toy story 2", "zootopia"],
    ["Thumbelina"],
    ["The thing"],
    ["The fifth element"],
    ["To Wong Foo, Thanks For Everything!"],
    ["Legend"],
    ["Harold and Maude"],
    ["Return to Oz"],
    ["E.T.", "Eternal sunshine of the spotless mind"],
    ["Mrs Doubtfire"],
    ["How to train your dragon"],
    ["Smokey and the Bandit"],
    ["Independence Day"],
    ["The Mummy"],
    ["Waking Life"],
    ["House of Flying Daggers"],
    ["A Beautiful Mind"],
    ["Across the Universe"],
    ["Lion King"],
    ["What Dreams May Come"],
    ["The Usual Suspects"],
    ["The Big Lebowski"],
    ["Into the SpiderVerse"],
    ["The Martian"],
    ["History of the World", "Spaceballs"],
    ["Beetlejuice"],
    ["The Cat From Outer Space"],
    ["The Nightmare Before Christmas"],
    ["Big Fish", "Eternal Sunshine of the Spotless Mind"],
    ["Secondhand Lions"],
    ["Twister"],
    ["Big Fish"],
    ["Hot Fuzz"],
    ["Superbad"],
    ["HOCUS POCUS"],
    ["Fern Gully"],
    ["Princess Mononoke"],
    ["Charlotte's Web"],
    ["Lion king", "Mulan"],
    ["50 First Dates"],
    ["Spirited away"],
    ["The Chronicles of Narnia"],
    ["Lost in Translation"],
    ["Shawshank Redemption", "Forrest Gump"],
    ["The Fountain"],
    ["The Secret Life of Walter Mitty"],
]


def find_movies_in_comments(dataset, searchset, comments):
    for i in range(0, len(searchset)):
        text = comments[i]["body"]
        searchText = searchset[i]
        value = {"entities": []}
        # print("text: " + text)
        for x in searchText:
            # print("\t searching for: " + x)
            start = text.index(x)
            wordLength = len(x)
            value["entities"].append((start, start + wordLength, "movie"))
        dataset.append((text, value))


# Function calls
TRAINING_DATA = [
    ("It's only getting better as the years pass!", {"entities": []}),
    (
        "That movie really is something else. It's funny, sad, exciting, sad, filled with action, sad, great music as well! Magical. I cry everytime.",
        {"entities": []},
    ),
    (
        "It's really cool when movies get to you even though they're about something you're not really into!",
        {"entities": []},
    ),
    ('"Death is a disease."', {"entities": []}),
    ("To each his own! :D", {"entities": []}),
    ("Yeah that one really is magical!", {"entities": []}),
    ("I love that one as well!", {"entities": []}),
    ("Brief nudity warning", {"entities": []}),
    ("Fuck yes. Have me nightmares as a kid but I love it so much", {"entities": []}),
]

find_movies_in_comments(TRAINING_DATA, search, comments)
# print(len(TRAINING_DATA))
with open("training_data_500.py", "a", encoding="utf-8") as outputFile:
    outputFile.write(str(TRAINING_DATA))
outputFile.close()


# print(len(search))
