import spacy

nlp1 = spacy.load(".\output\model-last")  # load the best model

test_sample = [
    {
        "author": {
            "name": "aqualily6",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_04_24A0ED.png",
        },
        "body": "Anastasia",
        "body_html": '<div class="md"><p>Anastasia</p>\n</div>',
        "comment_id": "gvmdamb",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmdamb/",
        "replies": ["gvmdin8", "gvme313", "gvmf48z", "gvmfgtu", "gvmfx7p"],
        "score": 10,
    },
    {
        "author": {
            "name": "TheyCallMeTerryTibbs",
            "avatar": "https://styles.redditmedia.com/t5_3xqfxk/styles/profileIcon_snoo556a6192-d327-4466-aba5-0024f56be932-headshot.png?width=256&height=256&crop=256:256,smart&s=397b6228148bca62e25f1e71102d172202e44005",
        },
        "body": "Coming to America (1988)",
        "body_html": '<div class="md"><p>Coming to America (1988)</p>\n</div>',
        "comment_id": "gvmdg1k",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmdg1k/",
        "replies": [],
        "score": 11,
    },
    {
        "author": {
            "name": "incaman88",
            "avatar": "https://styles.redditmedia.com/t5_clz8x/styles/profileIcon_snooa6bbd2e6-2a3b-4689-aaf3-4bef0abc7419-headshot.png?width=256&height=256&crop=256:256,smart&s=cbbdf57c476406a2b3d3e0990af3a359f44c5815",
        },
        "body": "Lock Stock & 2 Smoking Barrels. Fucking love this movie. I can rewatch it in my head, but still sit my ass for 2 hours to watch it. \n\n\u2014Is this some white cunts joke that black cunts don\u2019t get? Cause I\u2019m not fucking laughing NICHOLAS!",
        "body_html": '<div class="md"><p>Lock Stock &amp; 2 Smoking Barrels. Fucking love this movie. I can rewatch it in my head, but still sit my ass for 2 hours to watch it. </p>\n\n<p>\u2014Is this some white cunts joke that black cunts don\u2019t get? Cause I\u2019m not fucking laughing NICHOLAS!</p>\n</div>',
        "comment_id": "gvmksrj",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmksrj/",
        "replies": [],
        "score": 11,
    },
    {
        "author": {
            "name": "dreamless-circuits",
            "avatar": "https://styles.redditmedia.com/t5_2ks0nx/styles/profileIcon_snoo384f7e0b-7320-4953-834e-f1e00871a647-headshot.png?width=256&height=256&crop=256:256,smart&s=b1253964766003136fcdb8b461fe30eb4d6d0bb8",
        },
        "body": "Garden State. So close to home and such a beautiful and magical story. Really brings the feels.",
        "body_html": '<div class="md"><p>Garden State. So close to home and such a beautiful and magical story. Really brings the feels.</p>\n</div>',
        "comment_id": "gvmm77z",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmm77z/",
        "replies": [],
        "score": 10,
    },
    {
        "author": {
            "name": "Electronic-Amount587",
            "avatar": "https://styles.redditmedia.com/t5_36ucuw/styles/profileIcon_snoo92c6af2f-9420-4481-a367-72ec29ca1193-headshot.png?width=256&height=256&crop=256:256,smart&s=1f6609a8977a238b940bd2e68573730195f0b99e",
        },
        "body": "Zootopia. That movie is so great and wholesome.",
        "body_html": '<div class="md"><p>Zootopia. That movie is so great and wholesome.</p>\n</div>',
        "comment_id": "gvmn98n",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmn98n/",
        "replies": [],
        "score": 9,
    },
    {
        "author": {
            "name": "delphio",
            "avatar": "https://styles.redditmedia.com/t5_r7v1u/styles/profileIcon_snoo4599d716-5732-4d8c-b44b-6df037966b26-headshot.png?width=256&height=256&crop=256:256,smart&s=9ce98c19fede5593107b94898510cb5bda1577bc",
        },
        "body": "The Color Purple (1985 Spielberg film).\n\nParticularly two scenes, one where Celie (Whoopi Goldberg) is imagining her children living in Africa while shaving Mister (Danny Glover), and the one where Shug Avery (Margaret Avery) sings \"God is tryin to tell you somethin\" while quickly walking to her father's church. Any of the many magical scenes with Shug or Celie's sister Nettie (Akosua Busia) as well.",
        "body_html": '<div class="md"><p>The Color Purple (1985 Spielberg film).</p>\n\n<p>Particularly two scenes, one where Celie (Whoopi Goldberg) is imagining her children living in Africa while shaving Mister (Danny Glover), and the one where Shug Avery (Margaret Avery) sings &quot;God is tryin to tell you somethin&quot; while quickly walking to her father&#39;s church. Any of the many magical scenes with Shug or Celie&#39;s sister Nettie (Akosua Busia) as well.</p>\n</div>',
        "comment_id": "gvmnw1a",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmnw1a/",
        "replies": [],
        "score": 12,
    },
    {
        "author": {
            "name": "2se_",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_10_FFD635.png",
        },
        "body": "Spirited Away",
        "body_html": '<div class="md"><p>Spirited Away</p>\n</div>',
        "comment_id": "gvlh098",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlh098/",
        "replies": ["gvlx38o", "gvlitgk"],
        "score": 28,
    },
    {
        "author": {
            "name": "miguel4546",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_19_0DD3BB.png",
        },
        "body": "Scream",
        "body_html": '<div class="md"><p>Scream</p>\n</div>',
        "comment_id": "gvlnhhp",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlnhhp/",
        "replies": ["gvmaozd", "gvmopwb", "gvmbu6w", "gvmc5l2", "gvmi3e6"],
        "score": 29,
    },
    {
        "author": {
            "name": "Thykk3r",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_06_0079D3.png",
        },
        "body": "Your Name - the music, animation, plot are all stunning",
        "body_html": '<div class="md"><p>Your Name - the music, animation, plot are all stunning</p>\n</div>',
        "comment_id": "gvlo743",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlo743/",
        "replies": ["gvm8rj1", "gvma93l", "gvmn7pp", "gvmn1j2"],
        "score": 29,
    },
    {
        "author": {
            "name": "slobeck",
            "avatar": "https://styles.redditmedia.com/t5_1bd5cx/styles/profileIcon_yhopxfrs87z41.jpg?width=256&height=256&crop=256:256,smart&s=4ac14aacd8057fdefd0b05838375538e845075e5",
        },
        "body": 'I feel like Imma put this up here and people are gonna be like "huh?"\n\nBut hear me out:  "Excalibur" 1983 Dir: John Boorman. A 3 hour-long nearly flawless adaptation of Sir Thomas Mallory 15th Century masterwork "La Mort D\'Arthur" (The Death of Arthur) Which is the tale of King Arthur we know today from the sword in the stone, Merlin, the betrayal by Lancelot and Lady Genevieve, the quest for the holy grail and his eventual demise at the hand of his bastard son.\n\nIt has Merlin\'s doomed  "Charm of Making" which nearly every fan of this film knows by heart.\n\nYoung (and hawt) Dame Helen Mirren as Morgana the witch.\n\nBest. Movie. Ever.',
        "body_html": '<div class="md"><p>I feel like Imma put this up here and people are gonna be like &quot;huh?&quot;</p>\n\n<p>But hear me out:  &quot;Excalibur&quot; 1983 Dir: John Boorman. A 3 hour-long nearly flawless adaptation of Sir Thomas Mallory 15th Century masterwork &quot;La Mort D&#39;Arthur&quot; (The Death of Arthur) Which is the tale of King Arthur we know today from the sword in the stone, Merlin, the betrayal by Lancelot and Lady Genevieve, the quest for the holy grail and his eventual demise at the hand of his bastard son.</p>\n\n<p>It has Merlin&#39;s doomed  &quot;Charm of Making&quot; which nearly every fan of this film knows by heart.</p>\n\n<p>Young (and hawt) Dame Helen Mirren as Morgana the witch.</p>\n\n<p>Best. Movie. Ever.</p>\n</div>',
        "comment_id": "gvlt1cj",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlt1cj/",
        "replies": [
            "gvlyezt",
            "gvmkh8e",
            "gvmp9o9",
            "gvmixjh",
            "gvmj65i",
            "gvmp59p",
            "gvn3own",
            "gvm07vh",
            "gvn2ilw",
            "gvm2koj",
            "gvnagre",
        ],
        "score": 28,
    },
    {
        "author": {
            "name": "MannibalTheBannibal",
            "avatar": "https://styles.redditmedia.com/t5_27mv8p/styles/profileIcon_snoo27bbb3c0-cc79-4217-8f07-7c03b5aed3e8-headshot.png?width=256&height=256&crop=256:256,smart&s=d3961e7e6d2c46883fc40ffabe597020137110db",
        },
        "body": "Moulin Rouge. Amazing music, great acting that makes me cry still after watching it over 100 times, absolutely STUNNING costumes and sets. Thats just my idea of the perfect film",
        "body_html": '<div class="md"><p>Moulin Rouge. Amazing music, great acting that makes me cry still after watching it over 100 times, absolutely STUNNING costumes and sets. Thats just my idea of the perfect film</p>\n</div>',
        "comment_id": "gvlv7mn",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlv7mn/",
        "replies": ["gvnjoi4"],
        "score": 30,
    },
    {
        "author": {
            "name": "Spacy256",
            "avatar": "https://styles.redditmedia.com/t5_ohdte/styles/profileIcon_snoo5368434f-057c-4c0c-8c90-81901ca0c379-headshot.png?width=256&height=256&crop=256:256,smart&s=4649c8b8e673962d9c4e633e25e1dd8bc7914d14",
        },
        "body": "Pink Floyd's the Wall. Fantastic and trippy movie",
        "body_html": '<div class="md"><p>Pink Floyd&#39;s the Wall. Fantastic and trippy movie</p>\n</div>',
        "comment_id": "gvm0pt1",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm0pt1/",
        "replies": ["gvnotrw"],
        "score": 31,
    },
    {
        "author": {
            "name": "oopsy-daisy6837",
            "avatar": "https://styles.redditmedia.com/t5_2xwbqn/styles/profileIcon_-QpJIiMJxbNuY.png?width=256&height=256&crop=256:256,smart&s=fdf5faee503b466118377b312ba3c51cc180a8ae",
        },
        "body": "Cloud Atlas",
        "body_html": '<div class="md"><p>Cloud Atlas</p>\n</div>',
        "comment_id": "gvm3a2y",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm3a2y/",
        "replies": ["gvn72xa", "gvmaoyo", "gvmljhg", "gvnosex"],
        "score": 30,
    },
    {
        "author": {
            "name": "goldenhaz",
            "avatar": "https://styles.redditmedia.com/t5_3bfyz9/styles/profileIcon_snoo238dc2bf-1a57-4adb-adbe-731d7c6b15bc-headshot.png?width=256&height=256&crop=256:256,smart&s=71693aee807c9ff20c8414c24de4231d1518be5b",
        },
        "body": "Barbie & the Diamond Castle",
        "body_html": '<div class="md"><p>Barbie &amp; the Diamond Castle</p>\n</div>',
        "comment_id": "gvloocu",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvloocu/",
        "replies": [],
        "score": 9,
    },
    {
        "author": {
            "name": "AlanZero",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_03_25B79F.png",
        },
        "body": "Goon",
        "body_html": '<div class="md"><p>Goon</p>\n</div>',
        "comment_id": "gvlpq3a",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlpq3a/",
        "replies": ["gvmmvud", "gvmp7t2", "gvovyhh"],
        "score": 9,
    },
    {
        "author": {
            "name": "scotti_infinity_x",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_15_D4E815.png",
        },
        "body": "Hugo",
        "body_html": '<div class="md"><p>Hugo</p>\n</div>',
        "comment_id": "gvlsosn",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlsosn/",
        "replies": ["gvm8702"],
        "score": 9,
    },
    {
        "author": {
            "name": "oowoops",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_04_7E53C1.png",
        },
        "body": "2004 Van Helsing Ft. Hugh Jackman",
        "body_html": '<div class="md"><p>2004 Van Helsing Ft. Hugh Jackman</p>\n</div>',
        "comment_id": "gvlwr26",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlwr26/",
        "replies": [],
        "score": 7,
    },
    {
        "author": {
            "name": "Jorjaislove",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_16_94E044.png",
        },
        "body": "Spirited away",
        "body_html": '<div class="md"><p>Spirited away</p>\n</div>',
        "comment_id": "gvm2i7h",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm2i7h/",
        "replies": [],
        "score": 9,
    },
    {
        "author": {
            "name": "cavett",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_05_94E044.png",
        },
        "body": "The Adventures of Baron von Munchausen, though I haven't seen it in years fond memories still persist.",
        "body_html": '<div class="md"><p>The Adventures of Baron von Munchausen, though I haven&#39;t seen it in years fond memories still persist.</p>\n</div>',
        "comment_id": "gvm2w2d",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm2w2d/",
        "replies": [],
        "score": 9,
    },
    {
        "author": {
            "name": "asystolesfw",
            "avatar": "https://styles.redditmedia.com/t5_31tel0/styles/profileIcon_snoo0201e04a-4039-4a1f-9344-cb104278c293-headshot.png?width=256&height=256&crop=256:256,smart&s=04fcfb6829e00ed0b9fb4682037823d3b2fca4e3",
        },
        "body": "The Princess Bride",
        "body_html": '<div class="md"><p>The Princess Bride</p>\n</div>',
        "comment_id": "gvm3my6",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm3my6/",
        "replies": [],
        "score": 8,
    },
    {
        "author": {
            "name": "Then_News",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_01_7E53C1.png",
        },
        "body": "Dances With Wolves",
        "body_html": '<div class="md"><p>Dances With Wolves</p>\n</div>',
        "comment_id": "gvm3y5y",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm3y5y/",
        "replies": ["gvnadnk"],
        "score": 9,
    },
    {
        "author": {
            "name": "unicorndragons88",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_17_DB0064.png",
        },
        "body": "The Last Unicorn. \n\nWhen she tells Schmindrick that she will always be human because she regrets, it resonates with me.",
        "body_html": '<div class="md"><p>The Last Unicorn. </p>\n\n<p>When she tells Schmindrick that she will always be human because she regrets, it resonates with me.</p>\n</div>',
        "comment_id": "gvm40wj",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm40wj/",
        "replies": [],
        "score": 8,
    },
    {
        "author": {
            "name": "esoteric_enigma",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_08_545452.png",
        },
        "body": "I loved Lady in the Water. I rewatched it so many times on HBO. I didn't discover until years later that people hated it and it was critically panned.",
        "body_html": '<div class="md"><p>I loved Lady in the Water. I rewatched it so many times on HBO. I didn&#39;t discover until years later that people hated it and it was critically panned.</p>\n</div>',
        "comment_id": "gvm6r5g",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm6r5g/",
        "replies": ["gvmvajb", "gvn61rs", "gvnb5r7"],
        "score": 10,
    },
    {
        "author": {
            "name": "fractoral",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_14_DB0064.png",
        },
        "body": "The Secret of NIMH.  It gets me everytime, and it's also the only thing I want to watch whenever I'm stuck-on-couch sick.",
        "body_html": '<div class="md"><p>The Secret of NIMH.  It gets me everytime, and it&#39;s also the only thing I want to watch whenever I&#39;m stuck-on-couch sick.</p>\n</div>',
        "comment_id": "gvm74xb",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm74xb/",
        "replies": [],
        "score": 7,
    },
    {
        "author": {
            "name": "RampantSavagery",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_12_24A0ED.png",
        },
        "body": "Hot Fuzz. A masterpiece.",
        "body_html": '<div class="md"><p>Hot Fuzz. A masterpiece.</p>\n</div>',
        "comment_id": "gvm7hjp",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm7hjp/",
        "replies": [],
        "score": 9,
    },
    {
        "author": {
            "name": "iCaliban13",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_13_7E53C1.png",
        },
        "body": "Chronicles of Riddick. Or almost any Vin diesel movie",
        "body_html": '<div class="md"><p>Chronicles of Riddick. Or almost any Vin diesel movie</p>\n</div>',
        "comment_id": "gvm7obl",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm7obl/",
        "replies": ["gvn0qqh", "gvn0zm1", "gvn4dsu"],
        "score": 8,
    },
    {
        "author": {
            "name": "xGoldenBurgerx",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_06_FF8717.png",
        },
        "body": "Oh brother where art thou",
        "body_html": '<div class="md"><p>Oh brother where art thou</p>\n</div>',
        "comment_id": "gvm86s7",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm86s7/",
        "replies": [],
        "score": 10,
    },
    {
        "author": {
            "name": "luthorhuss",
            "avatar": "https://styles.redditmedia.com/t5_b3oxj/styles/profileIcon_snoo1cc3bc47-b592-45af-890e-83f9e6804d60-headshot.png?width=256&height=256&crop=256:256,smart&s=958f23a0984792005d1ddac342dcae6ca6be8bbe",
        },
        "body": "The 13th Warrior. I am little biased because I read the short story first, which was inspired by real life writings. The fact that an Arabic scribe ventured onto a Viking longship and wrote about their culture is fascinating to me. Combine that with the absolutely genius way that superstition is handled alongside tradition, comedy, tragedy and language in the film and I could watch this film for infinity and still love it. So many masterful scenes and done in a way where you 100% believe any of it could\u2019ve happened. The cinematography and score are top notch and it\u2019s a shame that many ppl see Antonio Banderas (who holds his own in the film) and immediately write it off as a cheap action flick. If you love history or are tired of the same old film, read Crichton\u2019s \u201cEaters of the Dead\u201d short story then watch this.",
        "body_html": '<div class="md"><p>The 13th Warrior. I am little biased because I read the short story first, which was inspired by real life writings. The fact that an Arabic scribe ventured onto a Viking longship and wrote about their culture is fascinating to me. Combine that with the absolutely genius way that superstition is handled alongside tradition, comedy, tragedy and language in the film and I could watch this film for infinity and still love it. So many masterful scenes and done in a way where you 100% believe any of it could\u2019ve happened. The cinematography and score are top notch and it\u2019s a shame that many ppl see Antonio Banderas (who holds his own in the film) and immediately write it off as a cheap action flick. If you love history or are tired of the same old film, read Crichton\u2019s \u201cEaters of the Dead\u201d short story then watch this.</p>\n</div>',
        "comment_id": "gvm9adk",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvm9adk/",
        "replies": ["gvmnc8v", "gvmwxzk", "gvn4v26", "gvn7h9e"],
        "score": 8,
    },
    {
        "author": {
            "name": "MsGMF",
            "avatar": "https://styles.redditmedia.com/t5_2p3l0e/styles/profileIcon_snoo23286ca2-255a-46ab-89a2-22123d17b020-headshot.png?width=256&height=256&crop=256:256,smart&s=195b2f41c06142b2e1942eec302ad190a74b562c",
        },
        "body": "Saving this thread for when I can\u2019t decide what to watch on Netflix",
        "body_html": '<div class="md"><p>Saving this thread for when I can\u2019t decide what to watch on Netflix</p>\n</div>',
        "comment_id": "gvmau9q",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmau9q/",
        "replies": ["gvmyfj2"],
        "score": 9,
    },
    {
        "author": {
            "name": "FuckTrumpBanTheHateR",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_16_A06A42.png",
        },
        "body": "I'm late to the party, but despite the horrible 80's cgi, The Last Starfighter will always be one of my favorite movies.",
        "body_html": '<div class="md"><p>I&#39;m late to the party, but despite the horrible 80&#39;s cgi, The Last Starfighter will always be one of my favorite movies.</p>\n</div>',
        "comment_id": "gvmb6m6",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmb6m6/",
        "replies": ["gvnf0qr"],
        "score": 11,
    },
    {
        "author": {
            "name": "TonyRocky-Horror",
            "avatar": "https://styles.redditmedia.com/t5_2bp7sw/styles/profileIcon_y3an2su69qo41.jpg?width=256&height=256&crop=256:256,smart&s=98c7d14e1772cf29b4852549b06a08db4e0b87ad",
        },
        "body": "Little Shop of Horrors...Levi Stubbs gave that plant Soul, Steve Martin is unforgettable, and Rick Moranis is perfect.",
        "body_html": '<div class="md"><p>Little Shop of Horrors...Levi Stubbs gave that plant Soul, Steve Martin is unforgettable, and Rick Moranis is perfect.</p>\n</div>',
        "comment_id": "gvmeipq",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmeipq/",
        "replies": ["gvmez5g", "gvmmj4s"],
        "score": 10,
    },
    {
        "author": {
            "name": "ReptarOrgy",
            "avatar": "https://styles.redditmedia.com/t5_3ttnpq/styles/profileIcon_snoo73bc6827-754c-4880-bac0-bd444dc38704-headshot.png?width=256&height=256&crop=256:256,smart&s=e6d542d892e8d6179eea521f47db2d0881f31376",
        },
        "body": "Little Miss Sunshine. Everytime I watch it my emotions unravel",
        "body_html": '<div class="md"><p>Little Miss Sunshine. Everytime I watch it my emotions unravel</p>\n</div>',
        "comment_id": "gvmepcu",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvmepcu/",
        "replies": [],
        "score": 10,
    },
    {
        "author": {
            "name": "ghostofHamilton9488",
            "avatar": "https://styles.redditmedia.com/t5_26k9uu/styles/profileIcon_snoo458a7a0a-fb97-4561-bf2f-b1040ae52e0d-headshot.png?width=256&height=256&crop=256:256,smart&s=75f9c93ac17f10aceec147eeb1a651eedc82c271",
        },
        "body": "Shark boy and Lavagirl\u2014solely because of the movie\u2019s message",
        "body_html": '<div class="md"><p>Shark boy and Lavagirl\u2014solely because of the movie\u2019s message</p>\n</div>',
        "comment_id": "gvllb6g",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvllb6g/",
        "replies": [
            "gvls93t",
            "gvm2rh5",
            "gvm9aq9",
            "gvmbpoh",
            "gvmzcx6",
            "gvlsmmg",
            "gvmcpxf",
            "gvmzf4g",
            "gvmawy9",
            "gvm4ehd",
            "gvminv7",
            "gvn4m5m",
            "gvmdgy9",
            "gvm4hua",
        ],
        "score": 62,
    },
    {
        "author": {
            "name": "AffectionateShoe5447",
            "avatar": "https://styles.redditmedia.com/t5_42cgcn/styles/profileIcon_snoo906f0527-af03-4ca5-8f46-dae9afeeb5a6-headshot.png?width=256&height=256&crop=256:256,smart&s=2575efa902b0f72ec79a376bf68beddb7eb59c38",
        },
        "body": "Ghibli! All of them!",
        "body_html": '<div class="md"><p>Ghibli! All of them!</p>\n</div>',
        "comment_id": "gvlrcjg",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlrcjg/",
        "replies": ["gvm0655", "gvmb40s", "gvn0r7p", "gvm4hbs"],
        "score": 47,
    },
    {
        "author": {
            "name": "SterlingDullaghan",
            "avatar": "https://styles.redditmedia.com/t5_2eahtt/styles/profileIcon_snoodfb70e26-368e-45ce-a782-494b45fb5925-headshot.png?width=256&height=256&crop=256:256,smart&s=9280f7cefb0ed3602dd2a41a13105f174bc432c3",
        },
        "body": "Nacho Libre",
        "body_html": '<div class="md"><p>Nacho Libre</p>\n</div>',
        "comment_id": "gvlo1wk",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlo1wk/",
        "replies": [
            "gvmc3nz",
            "gvmfrvf",
            "gvmf2o8",
            "gvmilfi",
            "gvxfs1q",
            "gvme1kh",
            "gvme7vg",
            "gvmmpkm",
            "gvmes4h",
        ],
        "score": 37,
    },
    {
        "author": {
            "name": "GrantD97",
            "avatar": "https://styles.redditmedia.com/t5_2ilcq6/styles/profileIcon_snoo29e79a96-733e-4e7b-baed-3243f839b86c-headshot.png?width=256&height=256&crop=256:256,smart&s=5f33c9b8856160ef060e478b761a60d184664d59",
        },
        "body": "##Scott Pilgrim vs The World \n\nThe one movie that took my breath away the first day I saw it and never fails to give me the same experience with every new viewing. It\u2019s my favorite movie of all time, from the plot to the characterization, cinematography, pacing, script, casting, themes, references, costume design, score, even color pallets! \n\nEdgar Wright is *in my opinion* one of the most brilliant and creative directors to date, with Scott Pilgrim being some of his best work. It\u2019s always been my go-to comfort movie that I watch at least once a month or every other month to this very day. \n\nTruly a magical experience that I have yet to find with any other film.",
        "body_html": '<div class="md"><h2>Scott Pilgrim vs The World</h2>\n\n<p>The one movie that took my breath away the first day I saw it and never fails to give me the same experience with every new viewing. It\u2019s my favorite movie of all time, from the plot to the characterization, cinematography, pacing, script, casting, themes, references, costume design, score, even color pallets! </p>\n\n<p>Edgar Wright is <em>in my opinion</em> one of the most brilliant and creative directors to date, with Scott Pilgrim being some of his best work. It\u2019s always been my go-to comfort movie that I watch at least once a month or every other month to this very day. </p>\n\n<p>Truly a magical experience that I have yet to find with any other film.</p>\n</div>',
        "comment_id": "gvlpho4",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlpho4/",
        "replies": ["gvlw97t", "gvmexg7"],
        "score": 41,
    },
    {
        "author": {
            "name": "FolgersEnglish",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_05_FF585B.png",
        },
        "body": "Signs. People hate the ending but I love that movie from start to end",
        "body_html": '<div class="md"><p>Signs. People hate the ending but I love that movie from start to end</p>\n</div>',
        "comment_id": "gvlruqj",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlruqj/",
        "replies": ["gvmhpi1", "gvmlqfk", "gvnaym7"],
        "score": 37,
    },
    {
        "author": {
            "name": "Thot_robot_superman",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_06_FF4500.png",
        },
        "body": "Volcano with Tommy Lee Jones, I just like the movie",
        "body_html": '<div class="md"><p>Volcano with Tommy Lee Jones, I just like the movie</p>\n</div>',
        "comment_id": "gvllnac",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvllnac/",
        "replies": ["gvm34g9", "gvmdj14", "gvmh4a2"],
        "score": 23,
    },
    {
        "author": {
            "name": "FruitCupBoi",
            "avatar": "https://www.redditstatic.com/avatars/avatar_default_18_008985.png",
        },
        "body": "Speed Racer",
        "body_html": '<div class="md"><p>Speed Racer</p>\n</div>',
        "comment_id": "gvlolm3",
        "permalink": "/r/AskReddit/comments/mx0pwd/what_movie_is_simply_magical_to_you_no_matter_how/gvlolm3/",
        "replies": ["gvm6iz1", "gvma7v3", "gvn10zn"],
        "score": 26,
    },
]

print(len(test_sample))

with open("training_test_result.py", "w") as resultFile:
    for i in range(0, len(test_sample)):
        resultFile.write("Test #" + str(i) + "\n")
        resultFile.write("\ttext | " + test_sample[i]["body"] + "\n")
        doc = nlp1(test_sample[i]["body"])  # input sample text
        for entity in doc.ents:
            resultFile.write("\t" + entity.label_ + " | " + entity.text + "\n")
        resultFile.write("\n----------\n")

resultFile.close()
